# =============================================================================
# Google Cloud Build Configuration - HeyMello Next.js Frontend
# =============================================================================
# This config builds a Docker image and deploys to Cloud Run
# Triggered by: ./deploy.sh or GCP Build Triggers
# =============================================================================

steps:
  # Step 1: Build Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/${_SERVICE_NAME}:$BUILD_ID'
      - '-t'
      - 'gcr.io/$PROJECT_ID/${_SERVICE_NAME}:latest'
      - './frontend'
    timeout: '900s'

  # Step 2: Push image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - '--all-tags'
      - 'gcr.io/$PROJECT_ID/${_SERVICE_NAME}'

  # Step 3: Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'deploy'
      - '${_SERVICE_NAME}'
      - '--image'
      - 'gcr.io/$PROJECT_ID/${_SERVICE_NAME}:$BUILD_ID'
      - '--region'
      - '${_REGION}'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--port'
      - '3000'
      - '--memory'
      - '512Mi'
      - '--cpu'
      - '1'
      - '--min-instances'
      - '0'
      - '--max-instances'
      - '10'
      - '--timeout'
      - '300'
      - '--set-env-vars'
      - 'DATABASE_URL=${_DATABASE_URL},NODE_TLS_REJECT_UNAUTHORIZED=0,ENABLE_EMAILS=${_ENABLE_EMAILS},SMTP_HOST=${_SMTP_HOST},SMTP_PORT=${_SMTP_PORT},SMTP_SECURE=${_SMTP_SECURE},SMTP_USER=${_SMTP_USER},SMTP_PASSWORD=${_SMTP_PASSWORD},EMAIL_FROM=${_EMAIL_FROM},EMAIL_REPLY_TO=${_EMAIL_REPLY_TO}'

# =============================================================================
# Substitutions (Variables)
# =============================================================================
# Override with: --substitutions=_VAR=value
substitutions:
  _REGION: 'us-central1'
  _SERVICE_NAME: 'heymello-uat-website'
  _DATABASE_URL: 'postgresql://postgres:password@35.232.108.201:5432/website?sslmode=require'
  _ENABLE_EMAILS: 'false'
  _SMTP_HOST: ''
  _SMTP_PORT: '587'
  _SMTP_SECURE: 'false'
  _SMTP_USER: ''
  _SMTP_PASSWORD: ''
  _EMAIL_FROM: 'noreply@heymello.ai'
  _EMAIL_REPLY_TO: 'support@heymello.ai'

# =============================================================================
# Build Configuration
# =============================================================================
timeout: '1200s'  # 20 minutes max

options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'E2_HIGHCPU_8'
  
# Images to store in Container Registry
images:
  - 'gcr.io/$PROJECT_ID/${_SERVICE_NAME}:latest'
  - 'gcr.io/$PROJECT_ID/${_SERVICE_NAME}:$BUILD_ID'
